In [41]:
%load_ext autoreload
%autoreload 2

In [31]:
from pathlib import Path
import sys
import pandas as pd
import numpy as np

from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import joblib

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [ ]:
pitcher_games = pd.read_csv("../data/processed/pitcher_games_features_base.csv")

model = joblib.load("../models/xgboost.pkl")

with open("../models/model_features.json") as f:
    feature_cols = json.load(f)

In [5]:
pitcher_games["game_date"] = pd.to_datetime(pitcher_games["game_date"])

pitcher_games = pitcher_games.sort_values(["pitcher", "game_date"])

In [9]:
cutoff = pd.Timestamp("2024-08-01")

backtest_train = pitcher_games[pitcher_games["game_date"] < cutoff].copy()

backtest_test = pitcher_games[pitcher_games["game_date"] >= cutoff].copy()

In [12]:
backtest_model = Pipeline(
    [
        ("imputer", SimpleImputer(strategy="median")),
        (
            "xgb",XGBRegressor(
                objective="reg:squarederror",
                colsample_bytree=0.8,
                learning_rate=0.05,
                max_depth=3,
                n_estimators=100,
                subsample=1.0,
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

In [13]:
X_train = backtest_train[feature_cols]
y_train = backtest_train["strikeouts"]

X_test = backtest_test[feature_cols]
y_test = backtest_test["strikeouts"]

In [14]:
backtest_model.fit(X_train, y_train)

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('xgb',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=0.8, device=None,
                              early_stopping_rounds=None,
                              enable_categorical=True, eval_metric=None,
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=3, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=100, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [15]:
backtest_test["predicted_strikeouts"] = (backtest_model.predict(X_test))

In [16]:
backtest_test[["game_date", "player_name", "strikeouts", "predicted_strikeouts"]].head(20)

    game_date        player_name  strikeouts  predicted_strikeouts
10 2024-08-21  Verlander, Justin           6              4.946564
11 2024-08-27  Verlander, Justin           3              5.134508
12 2024-09-02  Verlander, Justin           3              4.908831
13 2024-09-08  Verlander, Justin           0              4.973015
14 2024-09-14  Verlander, Justin           2              4.835873
15 2024-09-20  Verlander, Justin           4              4.568579
16 2024-09-28  Verlander, Justin           5              4.994508
39 2024-08-01    Morton, Charlie           6              4.912133
40 2024-08-08    Morton, Charlie           3              3.160828
41 2024-08-13    Morton, Charlie           8              4.908707
42 2024-08-18    Morton, Charlie           7              5.136100
43 2024-08-24    Morton, Charlie           6              5.115816
44 2024-08-29    Morton, Charlie           7              5.372723
45 2024-09-04    Morton, Charlie           8              5.480002
46 2024-09-09    Morton, Charlie           7              5.673161
47 2024-09-15    Morton, Charlie           6              5.604875
48 2024-09-20    Morton, Charlie           3              5.647313
49 2024-09-29    Morton, Charlie           3              4.433991
58 2024-09-14      Scherzer, Max           2              5.088361
59 2024-08-21      Cueto, Johnny           1              4.621334

In [17]:
backtest_mae = mean_absolute_error(y_test, backtest_test["predicted_strikeouts"])

backtest_rmse = np.sqrt(mean_squared_error(y_test, backtest_test["predicted_strikeouts"]))

backtest_r2 = r2_score(y_test, backtest_test["predicted_strikeouts"])

print(f"Backtest MAE: {backtest_mae:.3f}")
print(f"Backtest RMSE: {backtest_rmse:.3f}")
print(f"Backtest R²: {backtest_r2:.3f}")

Backtest MAE: 1.729
Backtest RMSE: 2.157
Backtest R²: 0.250

In [18]:
backtest_test["prediction_rank"] = (backtest_test.groupby("game_date")["predicted_strikeouts"].rank(ascending=False, method="first"))

In [19]:
backtest_test[
    backtest_test["game_date"] == backtest_test["game_date"].iloc[0]
][
    [
        "game_date",
        "player_name",
        "predicted_strikeouts",
        "strikeouts",
        "prediction_rank"
    ]
].sort_values("prediction_rank")

,game_date,player_name,predicted_strikeouts,strikeouts,prediction_rank
2311,2024-08-21,"Flaherty, Jack",6.082962,5,1.0
3456,2024-08-21,"Gilbert, Logan",5.868623,7,2.0
1849,2024-08-21,"Manaea, Sean",5.754618,9,3.0
4777,2024-08-21,"Pepiot, Ryan",5.665019,5,4.0
2507,2024-08-21,"Webb, Logan",5.582415,6,5.0
4672,2024-08-21,"Rodríguez, Yariel",5.265855,6,6.0
1414,2024-08-21,"Fried, Max",5.143272,4,7.0
1132,2024-08-21,"Nola, Aaron",5.095207,5,8.0
845,2024-08-21,"Taillon, Jameson",5.093792,5,9.0
182,2024-08-21,"Gibson, Kyle",5.048908,5,10.0
622,2024-08-21,"Heaney, Andrew",5.046432,8,11.0
10,2024-08-21,"Verlander, Justin",4.946564,6,12.0
2425,2024-08-21,"Montgomery, Jordan",4.838580,4,13.0
4834,2024-08-21,"Spence, Mitch",4.677825,10,14.0
2630,2024-08-21,"Waldron, Matt",4.671989,3,15.0
59,2024-08-21,"Cueto, Johnny",4.621334,1,16.0
1321,2024-08-21,"Martinez, Nick",4.580229,3,17.0
1933,2024-08-21,"Cortes, Nestor",4.549901,4,18.0
4328,2024-08-21,"Parker, Mitchell",4.516806,6,19.0
3296,2024-08-21,"Myers, Tobias",4.361582,5,20.0
492,2024-08-21,"Lorenzen, Michael",4.234784,5,21.0
4689,2024-08-21,"Gordon, Tanner",4.214644,2,22.0
883,2024-08-21,"Germán, Domingo",4.197684,4,23.0
4119,2024-08-21,"Crochet, Garrett",4.182523,4,24.0
3932,2024-08-21,"Cantillo, Joey",4.172566,5,25.0
4284,2024-08-21,"Woods Richardson, Simeon",4.126936,7,26.0
1445,2024-08-21,"Irvin, Cole",3.576576,2,27.0
4541,2024-08-21,"Muñoz, Roddery",3.086868,2,28.0
4482,2024-08-21,"Criswell, Cooper",2.689524,4,29.0
4894,2024-08-21,"Brieske, Beau",1.741716,3,30.0

In [20]:
backtest_test["decision"] = np.where(backtest_test["predicted_strikeouts"] >= 5.0, "START", "SIT")

In [ ]:
backtest_test[["game_date", "player_name", "predicted_strikeouts", "strikeouts", "decision"]].head(20)

    game_date        player_name  predicted_strikeouts  strikeouts decision
10 2024-08-21  Verlander, Justin              4.946564           6      SIT
11 2024-08-27  Verlander, Justin              5.134508           3    START
12 2024-09-02  Verlander, Justin              4.908831           3      SIT
13 2024-09-08  Verlander, Justin              4.973015           0      SIT
14 2024-09-14  Verlander, Justin              4.835873           2      SIT
15 2024-09-20  Verlander, Justin              4.568579           4      SIT
16 2024-09-28  Verlander, Justin              4.994508           5      SIT
39 2024-08-01    Morton, Charlie              4.912133           6      SIT
40 2024-08-08    Morton, Charlie              3.160828           3      SIT
41 2024-08-13    Morton, Charlie              4.908707           8      SIT
42 2024-08-18    Morton, Charlie              5.136100           7    START
43 2024-08-24    Morton, Charlie              5.115816           6    START
44 2024-08-29    Morton, Charlie              5.372723           7    START
45 2024-09-04    Morton, Charlie              5.480002           8    START
46 2024-09-09    Morton, Charlie              5.673161           7    START
47 2024-09-15    Morton, Charlie              5.604875           6    START
48 2024-09-20    Morton, Charlie              5.647313           3    START
49 2024-09-29    Morton, Charlie              4.433991           3      SIT
58 2024-09-14      Scherzer, Max              5.088361           2    START
59 2024-08-21      Cueto, Johnny              4.621334           1      SIT

In [ ]:
decision_summary = (backtest_test.groupby("decision")["strikeouts"].agg(games="count", average_actual_k="mean", median_actual_k="median"))

decision_summary

          games  average_actual_k  median_actual_k
decision
SIT         892          3.952915              4.0
START       750          5.834667              6.0

In [23]:
backtest_test["actual_success"] = (backtest_test["strikeouts"] >= 5)

decision_accuracy = (backtest_test.groupby("decision")["actual_success"].mean())

decision_accuracy

decision
SIT      0.387892
START    0.694667
Name: actual_success, dtype: float64

In [24]:
backtest_test[["game_date", "player_name", "predicted_strikeouts", "strikeouts", "decision"]].sort_values("predicted_strikeouts", ascending=False).head(10)

      game_date      player_name  predicted_strikeouts  strikeouts decision
1165 2024-08-12     Snell, Blake              8.622433          11    START
1168 2024-08-30     Snell, Blake              7.694146           8    START
1172 2024-09-22     Snell, Blake              7.346352           9    START
1163 2024-08-02     Snell, Blake              7.329849          11    START
2953 2024-08-18  Valdez, Framber              7.318032           9    START
1164 2024-08-07     Snell, Blake              7.314189           8    START
1166 2024-08-18     Snell, Blake              7.296875          10    START
3511 2024-08-07    Skubal, Tarik              7.277342           9    START
2146 2024-09-11    King, Michael              7.259226           6    START
2952 2024-08-12  Valdez, Framber              7.221440           9    START

In [25]:
backtest_test["prediction_error"] = (backtest_test["strikeouts"] - backtest_test["predicted_strikeouts"])

backtest_test[["game_date", "player_name", "predicted_strikeouts", "strikeouts", "prediction_error"]].sort_values("prediction_error", key=abs, ascending=False).head(10)

,game_date,player_name,predicted_strikeouts,strikeouts,prediction_error
3683,2024-08-24,"Francis, Bowden",4.689429,12,7.310571
3816,2024-09-27,"Detmers, Reid",4.835805,12,7.164195
4782,2024-09-18,"Pepiot, Ryan",5.111944,12,6.888056
4237,2024-09-13,"Marsh, Alec",4.394040,11,6.605960
4436,2024-08-10,"Arrighetti, Spencer",6.420976,13,6.579024
5020,2024-09-19,"Pfaadt, Brandon",5.445427,12,6.554573
2054,2024-09-18,"Ober, Bailey",5.517276,12,6.482724
761,2024-08-31,"Kikuchi, Yusei",5.757446,12,6.242554
5206,2024-09-29,"Birdsong, Hayden",4.888429,11,6.111571
4435,2024-08-04,"Arrighetti, Spencer",5.914933,12,6.085067

In [26]:
overall_avg_k = backtest_test["strikeouts"].mean()

start_avg_k = (backtest_test.loc[backtest_test["decision"] == "START", "strikeouts"].mean())

sit_avg_k = (backtest_test.loc[backtest_test["decision"] == "SIT", "strikeouts"].mean())

print(f"Overall average K: {overall_avg_k:.3f}")
print(f"START average K: {start_avg_k:.3f}")
print(f"SIT average K: {sit_avg_k:.3f}")
print(f"START advantage: " f"{start_avg_k - overall_avg_k:.3f} Ks")

Overall average K: 4.812
START average K: 5.835
SIT average K: 3.953
START advantage: 1.022 Ks

In [28]:
backtest_test.to_csv("../data/processed/model_evaluation_stats.csv", index=False)

stage5_summary = pd.DataFrame({
    "Metric": [
        "Backtest MAE",
        "Backtest RMSE",
        "Backtest R2",
        "START Games",
        "SIT Games",
        "START Avg K",
        "SIT Avg K",
        "START 5+ K Rate",
        "SIT 5+ K Rate"
    ],
    "Value": [
        backtest_mae,
        backtest_rmse,
        backtest_r2,
        750,
        892,
        5.834667,
        3.952915,
        0.694667,
        0.387892
    ]
})

stage5_summary.to_csv("../data/processed/stage5_results.csv", index=False)